# Generated by Django 3.2.12 on 2022-03-20 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_rename_reviews_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='live_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='repo_link',
            field=models.URLField(blank=True),
        ),
    ]
