# Generated by Django 3.2.12 on 2022-03-22 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20220320_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='review',
            name='approved',
            field=models.BooleanField(default=True),
        ),
    ]
